# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Génère une grille de Takuzu
#' @description Crée une grille de Takuzu de taille spécifiée avec un taux de remplissage défini
#' @param size La taille de la grille (nombre de lignes et de colonnes)
#' @param fillRate Le taux de remplissage de la grille (entre 0 et 1)
#' @return Une matrice d'entiers représentant la grille de Takuzu générée
#' @details
#' Cette fonction génère une grille de Takuzu partiellement remplie en respectant
#' les règles du jeu : pas plus de deux 0 ou deux 1 consécutifs, et autant de 0 que de 1
#' dans chaque ligne et colonne. Les cellules non remplies sont marquées par -1.
#' @export
generateTakuzu <- function(size, fillRate) {
  .Call(`_takuzuGame_generateTakuzu`, size, fillRate)
}


